### ISSUE TITLE
Dies if no SNR cube?

### ISSUE THREAD

**Issue by kmhess** [kmhess/SoFiA-image-pipeline#100]
Build in contingency if the SNR cube from SoFiA doesn't exist/isn't written out.  It appears that this happens if the parameterization is turned off...which leads to other catalog issues, but perhaps one has the case where there's only the mom0 map and the catalog, in which case, we'd still like to try and plot the contours.

First can check if chan.fits exists.  This + rms in catalog will allow SNR calculation.

Second can check if mask.fits exists.  This to calculate chan +rms will allow SNR calculation.

Last resort is to just take the rms from the catalog and plot contours as a function of rms in a single channel.  Should probably throw a warning in this case.

Kind of related to #20, and related to defining a minimum amount of required input to make images.

**Comment by paoloserra** [comment]
I think this is related to https://gitlab.com/SoFiA-Admin/SoFiA-2/-/issues/89 .

**Comment by kmhess** [comment]
Minor one line fix will be incoming...has to do with how latest python treats the truthiness of an element in a dictionary, apparently(?)
To do: mom1 and mom2 depend on snr maps because they are masked below some SNR value that determines the lowest HI contour.

**Comment by kmhess** [comment]
Close this issue when #70 is closed.
