### ISSUE TITLE
Instead of regridding...make images using just wcs?

### ISSUE THREAD

**Issue by kmhess** [kmhess/SoFiA-image-pipeline#15]
One place to speed up the code perhaps.  Needs to happen while maintaining consistent (and square) image sizes across spatial images.

**Comment by paoloserra** [comment]
For updates and discussion on this see #55 (now closed). The bottom line is that the solution proposed there and currently implemented in #57 (branch `noregrid`) does not work when ancillary image and HI products do not have the same epoch. So we need to find a way around that.
