### ISSUE TITLE
Make images without specifying a survey to overlay HI data on

### ISSUE THREAD

**Issue by kmhess** [kmhess/SoFiA-image-pipeline#20]
Basically just make the HI images, but make them look pretty, uniform, and square.

**Comment by rstofi** [comment]
Add a top-level option to disable background optical image query and download, to speed up the imaging of hundreds of sources

**Comment by kmhess** [comment]
I think offline will now work for everything except perhaps if PanSTARRS is requested.  Could probably do with some extensive testing though.

There's currently no built in option to force this mode.  The user has to actually be unable to access the urls that get requested.

**Comment by kmhess** [comment]
Thinking: rather than a command line option, allow user to do `-s none` to short circuit overlays and continue making the rest of the images.  To be implemented...
