### ISSUE TITLE
Add cache=False attempt if download fails

### ISSUE THREAD

**Issue by kmhess** [kmhess/SoFiA-image-pipeline#33]
Sometimes astroquery.SkyView doesn't work for unknown reasons for a source.  Caching is on to make things faster, but if it fails, try turning caching off...sometimes this encourages a download to work properly.

**Comment by paoloserra** [comment]
Unfortunately (?) I don't manage to reproduce my download issue at the moment, so I cannot test this.

As soon as I run into that problem again I will switch to this branch and give it a go. Sorry!

**Comment by kmhess** [comment]
No worries.  That's why I made it a separate branch for now...

**Comment by kmhess** [comment]
I'm going to go ahead and merge this into master for the release.  If SIP attempts cache=False, then the program prints that to the terminal, so we can keep an eye on it...
