### ISSUE TITLE
Contrast in PVD

### ISSUE THREAD

**Issue by paoloserra** [kmhess/SoFiA-image-pipeline#39]
When a source is very bright the PVD contrast is such that the noise is not visible. Example attached.

If we agree that the noise should show, then we should improve that part of the code.

<img width="929" alt="Screenshot 2022-04-11 at 10 08 12" src="https://user-images.githubusercontent.com/6591265/162692804-d660d598-ebb4-44bc-9d62-52e17d3f1dc7.png">

**Comment by kmhess** [comment]
I agree having the noise show would be nice as it would make sure the very faint emission is visible as well.  Picking a scaling scheme for all situations is tough.  Welcome to suggestions!

**Comment by paoloserra** [comment]
OK, let me give it a crack and make a PR for you to review.

**Comment by kmhess** [comment]
I like it.  I still miss seeing the variation above 3 sigma though, so I might think about adding a second color map above that threshold that isn't too distracting...
