### ISSUE TITLE
Global spectrum axis limits

### ISSUE THREAD

**Issue by healytwin1** [kmhess/SoFiA-image-pipeline#44]
The spectrum axis limits appear to be symmetric which is not ideal for high signal to noise galaxies, as in the attached plot.  

<img width="681" alt="image" src="https://user-images.githubusercontent.com/11073757/164492052-5a268694-5cac-43f8-b4e0-a8980daaaeca.png">

**Comment by paoloserra** [comment]
That's normally not the case. I have several examples with an asymmetric Y range. I think you may have hit the following

https://github.com/kmhess/SoFiA-image-pipeline/blob/31b07d39d96af245ba5d1c54e357bda558445a48/src/make_spectra.py#L119-L122

@kmhess is there a way we could change this? Maybe activate it only when TELESCOP = Apertif in the FITS header?

**Comment by kmhess** [comment]
Ooo, yeah.  Good point!  Well done previous me for leaving a note.  ;)  Should be a straightforward fix, I think.

**Comment by kmhess** [comment]
I changed how weird cases (like with RFI) on the full spectrum are detected and then how the limits are determined.  I'll probably have to iterate on the last part with Apertif, but this should fix @healytwin1's issue.
