### ISSUE TITLE
Problem when output.filename and output.directory from SoFiA are different from input

### ISSUE THREAD

**Issue by healytwin1** [kmhess/SoFiA-image-pipeline#45]
When I use the `-o` option to get the full spectrum with noise, I get the following error:

`FileNotFoundError: [Errno 2] No such file or directory: 'comb_10tracks_J1318_21_HI_r05_t60_mg085_3.image_mask.fits'`
at
```
  File "/Users/juliahealy/sofia/SoFiA-image-pipeline-master/image_pipeline.py", line 176, in <module>
    make_spectra.main(source, src_basename, original, suffix=suffix, beam=beam)
  File "/Users/juliahealy/sofia/SoFiA-image-pipeline-master/src/make_spectra.py", line 191, in main
    get_noise_spec(source, src_basename, cube_params, original)
  File "/Users/juliahealy/sofia/SoFiA-image-pipeline-master/src/make_spectra.py", line 38, in get_noise_spec
    mask = get_subcube(source, original[:-5] + '_mask.fits')
```

I think the mask base name should come from same prefix as the input catalogue.

**Comment by kmhess** [comment]
Hm...this might depend on how you ran SoFiA?  Did you give the SoFiA output a new name by setting `output.filename` or setting the `output.directory`?  That would be a condition that I hadn't tested for the `-o` setting.

**Comment by healytwin1** [comment]
I did provide both a new `output.filename` and specified the `output.directory`. What if you took the sofia parameter file as input, that would provide you with the location and names of all the files you need.

**Comment by paoloserra** [comment]
or maybe we could ask SoFiA to save that info in the XML catalogue header
