### ISSUE TITLE
Need a test cube in v_rad

### ISSUE THREAD

**Issue by kmhess** [kmhess/SoFiA-image-pipeline#49]
I think there may be a bug in lines 91-92 and 154-155 in src/make_spectra.py because this is changed to `v_col` in src/image_pipeline.py, but I need a test cube that is in radio velocity to properly check the work flow.

**Comment by kmhess** [comment]
Test cube provided by @vdhulst who has reported that SIP works well.  Will double check (especially with some pending PRs) and then close this issue.

**Comment by kmhess** [comment]
Output images are in optical even if cube has 'CTYPE3=VRAD'.  I think that astropy is doing a spectral conversion on the fly when it reads in the fits header because it reports 'CTYPE3=VELO-HEL' with different crpix3, crval3, cdelt3, as compared to a check with CARTA (see screenshot).  It also reports a different spatial projection (RA/DEC--NCP rather than RA/DEC--SIN).  Not sure if we should be worried about the latter and report it to astropy? 
<img width="1579" alt="Screen Shot 2022-06-06 at 11 36 29" src="https://user-images.githubusercontent.com/14857798/172136441-bc467ee2-78f0-4657-b4ec-11edb82fff91.png">
![n1365_1_combo](https://user-images.githubusercontent.com/14857798/172136478-6c7327f6-a798-4769-9067-a06ccb327f6c.png)

**Comment by kmhess** [comment]
I will probably complain to astropy about this automatic conversion (haven't yet found a way to turn it off).  The mom1 radio/optical convention can't be derived from the SoFiA mom1 data products because they don't maintain the CTYPE3 keyword, but they also can't be accurately derived form the original cube using astropy because it does the on-the-fly conversion.

**Comment by kmhess** [comment]
Welp...this is a CARTA issue not an astropy one.

**Comment by vdhulst** [comment]
> Welp...this is a CARTA issue not an astropy one.

not any more. I downloaded CARTA 3.0.0-beta.3 (10 May 2022) and it provides the proper header information. So somehow the CARTA folks realised this was wrong in earlier versions. My 'old' CARTA is version 1.4.0 (20200914)

**Comment by kmhess** [comment]
Thanks for checking Thijs!  CARTA 2.0.0 was also wrong, but glad the most recent version has been sorted.

**Comment by kmhess** [comment]
Okay, I think this has been resolved, and now I have a test cube in v_rad from MeerKAT. Closing this issue.
