### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by panstarrs** [kmhess/SoFiA-image-pipeline#51]
I run this command: sofia_image_pipeline -c ./sofia_test_output_cat.xml but get the below error. Is it something wrong with my SIP installation ? I used the pip to install it, thanks.

*****************************************************************
        Beginning SoFiA-image-pipeline (SIP).
        Reading catalog in XML format.
        WARNING: always assumes an xml file comes from SoFiA-2.
        Making figure directory.

        -Source 1: SoFiA J120120.94+615351.3.
        Start making spatial images.
        WARNING: Using deprecated EPOCH in header for equinox: J2000.0.
        Found BARYCENT reference frame specified in SPECSYS in header.
        Found CTYPE3 spectral axis type VELO-HEL in header.
        WARNING: dropping end of spectral axis type. Using SPECSYS/VELREF for reference frame.
        The first HI contour defined at SNR = [2.0, 3.0] has level = 2.829e+01 (mom0 data units).
        Image size bigger than default. Now 8.01 arcmin
        No user image given. Proceeding with the download of any requested archive images.
WARNING: AstropyDeprecationWarning: The truth value of a Quantity is ambiguous. In the future this will raise a ValueError. [astropy.units.quantity]
WARNING: InputWarning: Coordinate string is being interpreted as an ICRS coordinate. [astroquery.utils.commons]
Downloading https://skyview.gsfc.nasa.gov/tempspace/fits/skv6534653703077.fits
|===================================================================================================| 3.6M/3.6M (100.00%)         6s
        Survey image retrieved from DSS2 Blue.
        Making DSS2 Blue overlaid with HI contours.
WARNING: FITSFixedWarning: 'celfix' made the change 'Success'. [astropy.wcs.wcs]
/users/panh/.local/lib/python3.9/site-packages/astropy/visualization/wcsaxes/core.py:234: UserWarning: No contour levels were found within the data range.
  cset = super().contour(*args, **kwargs)
        Making HI grey scale map.
WARNING: FITSFixedWarning: 'celfix' made the change 'Success'. [astropy.wcs.wcs]
/users/panh/.local/lib/python3.9/site-packages/astropy/visualization/wcsaxes/core.py:234: UserWarning: No contour levels were found within the data range.
  cset = super().contour(*args, **kwargs)
        Making pixel SNR map.
WARNING: FITSFixedWarning: 'celfix' made the change 'Success'. [astropy.wcs.wcs]
        Making velocity map.
        WARNING: Assuming channels are uniform width in velocity.
        WARNING: Assuming channels are uniform width in velocity.
WARNING: FITSFixedWarning: 'celfix' made the change 'Success'. [astropy.wcs.wcs]
        Making pv slice.
        No pv fits file. Perhaps you ran source finding with an old version of SoFiA-2?
        Done making spatial images of the spectral line source 1: SoFiA J120120.94+615351.3.
        Start making spectral profiles
        WARNING: Using deprecated EPOCH in header for equinox: J2000.0.
        Found BARYCENT reference frame specified in SPECSYS in header.
        Found CTYPE3 spectral axis type VELO-HEL in header.
        WARNING: dropping end of spectral axis type. Using SPECSYS/VELREF for reference frame.
        Making HI SoFiA masked spectrum plot.
Traceback (most recent call last):
  File "/users/panh/.local/bin/sofia_image_pipeline", line 8, in <module>
    sys.exit(main())
  File "/users/panh/.local/lib/python3.9/site-packages/src/image_pipeline.py", line 196, in main
    make_spectra.main(source, src_basename, original, suffix=suffix, beam=beam)
  File "/users/panh/.local/lib/python3.9/site-packages/src/make_spectra.py", line 218, in main
    fig1, ax1_spec, outfile1 = make_spec(source, src_basename, cube_params, suffix=suffix)
  File "/users/panh/.local/lib/python3.9/site-packages/src/make_spectra.py", line 177, in make_spec
    while not ('f_sum' in spec.meta['comments'][ll] and 'chan' in spec.meta['comments'][ll] and
IndexError: list index out of range

**Comment by kmhess** [comment]
Hi, I think this is the error that arises from having run the source finding with an older version of SoFiA-2.  Check the *_spec.txt file for your first source.  The columns names should look like:
```
#        1                 2                 3         4
#     chan              freq             f_sum     n_pix
#        -                Hz           Jy/beam         -
#
```
where freq could also be v_rad, v_opt, or v_app.  Old versions of the *_spec.txt files looked like this but were changed because "Flux Density" as two words made the header impossible to read easily in python:
```
#  Channel         Frequency      Flux density    Pixels
#        -          Hz                      Jy         -
#
```
A quick fix would be to reformat the header, but please note the warning in the README that if you haven't run source finding with the latest version of SoFiA then we can't guarantee that the column density, line widths, or other parameters printed at the bottom of the figures will be correct in all instances.

**Comment by panstarrs** [comment]
Thanks, and yeah my *_spec.txt looks like the old version

I was running Sofia-2  2.4.1 below and thought this was the latest version, but I'll take a closer look at it

Using:    Source Finding Application (SoFiA)
  Version:  2.4.1 (24-Nov-2021)
  CPU:      OpenMP disabled
  Time:     Wed May 11 14:28:33 2022

**Comment by kmhess** [comment]
Great, thanks for posting the error and confirming!  This will be useful to point other users to that may have the same issue.  Let me know if you come across anything else. Best, Kelley

**Comment by kmhess** [comment]
Ah one more thought as far as the latest SoFiA-2 version...this might be the difference between the latest "release" and the latest development version on github.  I know SoFiA is planning a new official release, but in the meantime, you can try the development version.
