### ISSUE TITLE
PV along kinematical minor axis

### ISSUE THREAD

**Issue by paoloserra** [kmhess/SoFiA-image-pipeline#61]
This can be helpful for HI classification. As usual with these things, it might be better if it came straight out of SoFiA.

**Comment by kmhess** [comment]
Should I include it in the combo images in all cases?  If the user wants a full spectrum (like what we have inspecting the Apertif images), then the pv_min plot will run off the edge to the right and the plots will look a bit ragged in their organization.

**Comment by paoloserra** [comment]
mmmm true, how ragged is that?

maybe it could be optional, false by default for backward compatibility

**Comment by kmhess** [comment]
And next question...should I plot the minor axis PA on the velocity map as well or is that going to be "too busy" for the plot?

**Comment by paoloserra** [comment]
I'd find the second line useful (with arrow)

**Comment by kmhess** [comment]
Cool, do you know if SoFia outputs the minor axes as kin_pa + 90 or kin_pa - 90?

**Comment by paoloserra** [comment]
Good question... from the code it seems to be +90, but that could be in whatever system is used within SoFiA before final conversion, so I don't know whether it is +90 in the usual PA sense.
