### ISSUE TITLE
bug: image size for decals

### ISSUE THREAD

**Issue by panstarrs** [kmhess/SoFiA-image-pipeline#75]
Hi, it appears there is a limitation on the image size for the decals overlay. I used the -i 24 but the plot shows a much smaller size of ~14 arcmins. Do you know what's going on ?

**Comment by kmhess** [comment]
Hi, sorry for the long delayed in reply.  I believe this question is now answered, albeit indirectly, in #76: it appears there is a limit to the size of images from decals.  We don't currently have a solution, and it is probably outside the scope of SIP, but as suggested in that issue, we will shortly aim to make DR10 the default.
