### ISSUE TITLE
ImportError: cannot import name 'update_default_config' from 'astropy.config.configuration'

### ISSUE THREAD

**Issue by kmhess** [kmhess/SoFiA-image-pipeline#88]
The suggestion [here](https://stackoverflow.com/questions/77973744/cannot-import-name-update-default-config-from-astropy-config-configuration) is that this error is the result of some conflict between the latest version of astropy and (a version of) spectral-cube.  Previously we used spectral-cube to extract a PV slice, but since the latest versions of SoFiA-2 provide a PV slice as a fits file, we could remove this dependency.  

At the same time, this will hopefully remove any uncertainty in terms of differences in how the PV slices are extracted...although maybe we still need spectral-cube to extract the mask?  Worth double checking...

**Comment by kmhess** [comment]
Correction...we don't use spectral-cube, we use pvextractor.  But this still seems to be where the issue is coming from.  I can't import pvextractor at all at the moment without getting the same error.

**Comment by PeterKamphuis** [comment]
I'm getting this error as well, is there some way around it?

**Comment by PeterKamphuis** [comment]
ok, updating matplotlib and pvextractor apparently as done in #89

**Comment by kmhess** [comment]
Hey @PeterKamphuis thanks for letting me know you're running into this as well--and so raising the urgency with which I deal with it.  I will aim to run some checks and then update the code later this week.
