### ISSUE TITLE
Making moment-map2

### ISSUE THREAD

**Issue by csuvas** [kmhess/SoFiA-image-pipeline#90]
Hello, I'm currently utilizing SIP (SOFIA Image Pipeline) to generate SOFIA ) image products. While SIP successfully produces various products such as mom0-maps, mom1-maps, SNR (Signal-to-Noise Ratio) maps, etc., I'm encountering an issue generating the mom2-map. Could you kindly provide guidance on resolving this matter?

My input cubelets have mom2-map fits files

**Comment by kmhess** [comment]
Hi, thanks very much for your comment. Yes, you're right, at the moment SIP does not generate a mom2 map.  This is pending on our To Do list (see also #83).  I am aiming to address this at a planned development Busy Week at the beginning of June.  If you have a favorite, intuitive color map for visualizing mom2 maps, your suggestions would be very welcome.

**Comment by csuvas** [comment]
Hi, thanks for your response. Here are few color suggestions for mom2-map:   ***cmap**='**CM.jet'**  or RdBu or YlGnBu or '**

i would like to request you to add one more .txt file that stores the parameters values such as M(HI), optical depth, D(HI), etc from integrated spectra.

**Comment by kmhess** [comment]
Hi @csuvas, I've staged some changes in the mom2 branch, if you have the opportunity to test them and give feedback.

Thanks also for your other suggestions as well.  We actually prefer not to calculate M_HI, D_HI, etc because to do so requires one to make a choice in cosmology (e.g. Hubble constant), and we believe these choices are best left to the user, as it may depend on their science case/what other data they are comparing with.

**Comment by csuvas** [comment]
Thanks for your quick fix. Can you instruct me on how to install this specific version?  I tried installing this branch using `pip install git+https://github.com/kmhess/SoFiA-image-pipeline.git@mom2`. But while running now there are no moment maps - 0, 1 or 2. Even here the moment maps 0, 1 and DSS optical images are also missing which was present in the previous version.

I am getting this as the first few lines of the output 
```
No user specified image and no survey specified: will default to DSS2 Blue.
	Reading catalog in ascii format.
	Catalog generated by SoFiA-2?
	Making figure directory.

	-Source 1: SoFiAJ125859.28+290551.6.
	Start making spatial images.
	Found 15.3 arcsec by 6.3 arcsec beam with PA=-7.8 deg in primary header.
	Found J2000.0 equinox in header.
	Found BARYCENT reference frame specified in SPECSYS in header.
	Found CTYPE3 spectral axis type FREQ in header.
	The first HI contour defined at SNR = [2.0, 3.0] has level = 9.103e+04 (mom0 data units).
	No user image given. Proceeding with the download of any requested archive images.
	ERROR: "DSS2 Blue" may not among the survey hosted at skyview or survey names recognized by astroquery. 
		See SkyView.list_surveys or SkyView.survey_dict from astroquery for valid surveys.
	Making pv diagram.
	Attempting to overlay mask boundaries on pv diagram ...
|=======================================================================================================================================================================| 179 /179  (100.00%)         0s
	... done.
	Making pv_min diagram.
	No pv_min fits file. Perhaps you ran source finding with an old version of SoFiA-2?
	Done making spatial images.
	Start making spectral profiles
	Found 15.3 arcsec by 6.3 arcsec beam with PA=-7.8 deg in primary header.
	Found J2000.0 equinox in header.
	Found BARYCENT reference frame specified in SPECSYS in header.
	Found CTYPE3 spectral axis type FREQ in header.
	Making HI SoFiA masked spectrum plot.
	WARNING: Original data cube not provided: making spectrum of subcube with noise.
	Making HI spectrum plot including noise.
	Done making spectral profiles.
```

**Comment by kmhess** [comment]
Hm...okay, it seems like it can't find the DSS2 images, but I don't know why.  I'll investigate because I've seen this before.  In the mean time try running with `-s decals` and you'll get a false color image that's deeper than DSS2 anyway.

**Comment by kmhess** [comment]
@csuvas Okay, I think I've been able to solve the problem by requiring astroquery 0.4.7.  I don't really understand why the problem appeared, but this seemed to solve it.  I made some notes in #92, but this might only make sense to me after having dug into the code.  Anyway, try updating the branch and see if it works now.

**Comment by csuvas** [comment]
This time I get this error
```
Traceback (most recent call last):
  File "/mnt/home/student/csuvas/miniconda3/envs/sip2/bin/sofia_image_pipeline", line 8, in <module>
    sys.exit(main())
  File "/mnt/home/student/csuvas/miniconda3/envs/sip2/lib/python3.9/site-packages/src/image_pipeline.py", line 190, in main
    make_images.main(source, src_basename, opt_view=opt_view, suffix=suffix, sofia=sofia, beam=beam,
  File "/mnt/home/student/csuvas/miniconda3/envs/sip2/lib/python3.9/site-packages/src/make_images.py", line 1125, in main
    make_mom1(source, src_basename, cube_params, patch, opt_head, opt_view, HIlowest, suffix=suffix, sofia=2)
  File "/mnt/home/student/csuvas/miniconda3/envs/sip2/lib/python3.9/site-packages/src/make_images.py", line 518, in make_mom1
    cf = ax1.contour(mom1_d, colors=clevels, levels=levels, linewidths=0.6, transform=ax1.get_transform(cubew))
  File "/mnt/home/student/csuvas/miniconda3/envs/sip2/lib/python3.9/site-packages/astropy/visualization/wcsaxes/core.py", line 264, in contour
    transform_contour_set_inplace(cset, transform)
  File "/mnt/home/student/csuvas/miniconda3/envs/sip2/lib/python3.9/site-packages/astropy/visualization/wcsaxes/utils.py", line 176, in transform_contour_set_inplace
    vertices = transform.transform(vertices)
  File "/mnt/home/student/csuvas/miniconda3/envs/sip2/lib/python3.9/site-packages/matplotlib/transforms.py", line 1495, in transform
    res = self.transform_affine(self.transform_non_affine(values))
  File "/mnt/home/student/csuvas/miniconda3/envs/sip2/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 297, in wrapper
    return func(*args, **kwargs)
  File "/mnt/home/student/csuvas/miniconda3/envs/sip2/lib/python3.9/site-packages/matplotlib/transforms.py", line 2419, in transform_non_affine
    return self._b.transform_non_affine(self._a.transform(values))
  File "/mnt/home/student/csuvas/miniconda3/envs/sip2/lib/python3.9/site-packages/astropy/visualization/wcsaxes/wcsapi.py", line 318, in transform
    raise ValueError(
ValueError: Expected 2 world coordinates, got 0 
```

**Comment by kmhess** [comment]
Hm...okay, that's strange since the mom1 code hasn't been touched.  Do you get the same error for all sources or just for a particular one?  What survey are you attempting to plot the data on?  If you open the mom1.fits file for a failing source, does it have a detection (not filled with nan's)?  What version of matplotlib are you using?

**Comment by csuvas** [comment]
I am getting this issue for all the sources. The Mom file looks okay.

**Comment by kmhess** [comment]
@csuvas I found some data that reproduces this error.  For me it happens when using matplotlib >3.8, so I've modified the setup.py to specify versions less than this.  It is a fix for now until I can better understand why the error occurs in this version of matplotlib and not the earlier versions.  Please try pip installing the branch again and see if the error has disappeared.

**Comment by kmhess** [comment]
Unfortunately this isn't enough information to figure out what's going on.  Can you send me a sample cubelet and set of moment fits files for one source where this error occurs, and a single source catalog file containing the same source?

**Comment by kmhess** [comment]
@csuvas Unfortunately this isn't enough information to figure out what's going on. Can you send me a sample cubelet and set of moment fits files for one source where this error occurs, and a single source catalog file containing the same source?
